// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The action-cue discriminant. Each variant corresponds 1:1 to an
 * `ActionHistoryEntry` variant — derive it via `From<&ActionHistoryEntry>`
 * rather than naming both in parallel.
 */
export type ActionKind = "attack" | "move" | "pickUp" | "drop" | "escape" | "takeDamage" | "fumble" | "mechanicAction";
