// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItemRef } from "./ItemRef";
import type { RoomRef } from "./RoomRef";
import type { StatType } from "./StatType";
import type { TargetRef } from "./TargetRef";

export type ActionHistoryEntry = { "kind": "attack", round: bigint, target: TargetRef, } | { "kind": "move", round: bigint, room: RoomRef, } | { "kind": "pickUp", round: bigint, items: Array<ItemRef>, } | { "kind": "drop", round: bigint, items: Array<ItemRef>, } | { "kind": "escape", round: bigint, success: boolean, } | { "kind": "takeDamage", round: bigint, amount: number, stat: StatType, } | { "kind": "fumble", round: bigint, action: string, } | { "kind": "mechanicAction", round: bigint, mechanic: string, action: string, };
