// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Status } from "./Status";

export type Afflictions = { active: Partial<Record<Status, boolean>>; turnsActive: Partial<Record<Status, number>>; shakenOff: Status[]; immunity: Partial<Record<Status, number>>; };
