// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardScript } from "./CardScript";
import type { ExitScript } from "./ExitScript";
import type { ItemScript } from "./ItemScript";
import type { MechanicScript } from "./MechanicScript";
import type { NpcScript } from "./NpcScript";
import type { SceneScript } from "./SceneScript";
import type { VictoryScript } from "./VictoryScript";

/**
 * A scripted behavior, tagged on `family` (mechanic / exit / victory / item / npc / scene / card).
 */
export type BehaviorScript = { "family": "mechanic", script: MechanicScript, } | { "family": "exit", script: ExitScript, } | { "family": "victory", script: VictoryScript, } | { "family": "item", script: ItemScript, } | { "family": "npc", script: NpcScript, } | { "family": "scene", script: SceneScript, } | { "family": "card", script: CardScript, };
