// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Binary operators — restricted to the IEEE-754 operations that are
 * bit-identical between Rust and JS, plus comparisons and boolean logic.
 */
export type BinOp = "add" | "sub" | "mul" | "div" | "eq" | "ne" | "lt" | "lte" | "gt" | "gte" | "and" | "or";
