// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One card face in the Villain's hand, for surfaces to render.
 */
export type CardView = { key: string, name: string, text?: string, };
