// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One card face in the Villain's hand, for surfaces to render.
 */
export type CardView = { key: string, name: string, text?: string, 
/**
 * `true` when playing this card requires a target room (Shadow Step, or any
 * authored card with `config.target = "room"`), so surfaces can open a room
 * picker before dispatching. Absent otherwise.
 */
needsRoom?: boolean, };
