// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Stmt } from "./Stmt";

/**
 * A Wicked Ways card's author-defined behavior: the effect body fired when the
 * Villain plays the card. `on_play` is an effect body (`Vec<Stmt>`,
 * `allow_pass=false`, `allow_emit=true`), identical in shape to an item's
 * `on_use`. One-shot by construction — cards carry no persistent script state.
 */
export type CardScript = { onPlay?: Array<Stmt>, };
