// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
/**
 * A Wicked Ways card face — the display half of a card's identity. The card's
 * key doubles as its behavior key (native registry first, then a
 * `BehaviorScript::Card` in `catalog.behaviors`), mirroring how an item's
 * `behavior_key` doubles as its descriptor key.
 */
export type CardDescriptor = { name: string, 
/**
 * Rules/flavor text shown on the card face.
 */
text?: string, 
/**
 * Behavior-specific tuning read by the card op (e.g. `{"rounds": 2}` for
 * `wicked:lights-out`). Omitted when null.
 */
config?: unknown, };
