// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BehaviorScript } from "./BehaviorScript";
import type { FormationDescriptor } from "./FormationDescriptor";
import type { ItemDescriptor } from "./ItemDescriptor";
import type { RecipeMeta } from "./RecipeMeta";

export type Catalog = { items: { [key in string]?: ItemDescriptor }, aliases: { [key in string]?: Array<string> }, 
/**
 * Campaign-authored scripted behaviors, keyed by behavior key
 * (mechanic key / exit behaviorKey / victory condition key). Always emitted
 * (even when empty), byte-faithful to the `catalogFromRegistry` oracle,
 * which always writes this key; `default` keeps older keyless fixtures
 * deserializable.
 */
behaviors: { [key in string]?: BehaviorScript }, 
/**
 * Campaign-authored formation descriptors, keyed by encounter `behaviorKey`.
 * Always emitted (even when empty) to match the TS oracle; `default` keeps
 * older keyless fixtures deserializable.
 */
formations: { [key in string]?: FormationDescriptor }, 
/**
 * Campaign-authored crafting recipe metadata, keyed by recipe key. Always
 * emitted (even when empty) to match the TS oracle; `default` keeps older
 * keyless fixtures deserializable.
 */
recipes: { [key in string]?: RecipeMeta }, };
