// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Pure inputs to the mitigation formula. Field names cross the boundary in
 * camelCase — the wire shape is pinned by the conformance goldens.
 */
export type DamageInput = { attackStrength: number, armorSum: number, mitigator: number, lightAverse: boolean, roomLit: boolean, };
