// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Expr } from "./Expr";

/**
 * The body of a `modify_damage` transform. Tagged on `kind`.
 */
export type DamageBody = { "kind": "value", expr: Expr, } | { "kind": "final", expr: Expr, } | { "kind": "ifElse", cond: Expr, then: DamageBody, else: DamageBody, };
