// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a dialogue entry matches a player prompt. Tagged on `kind`; `Exact` is
 * full lowercased-string equality, `Fuzzy` is a token subset.
 */
export type DialogueMatch = { "kind": "exact", text: string, } | { "kind": "fuzzy", tokens: Array<string>, };
