// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MobAttack } from "./MobAttack";
import type { PresentationCue } from "./PresentationCue";

/**
 * The submit result. `mobAttacks` is present (possibly `[]`) on success and
 * ABSENT on the error path; `error` carries the `ProceduralViolation` message
 * verbatim. This shape is pinned by the conformance goldens.
 */
export type ExecuteResult = { cues: Array<PresentationCue>, mobAttacks?: Array<MobAttack>, error?: string, };
