// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Direction } from "./Direction";

/**
 * A passable exit as the surface lists it.
 */
export type ExitView = { dir: Direction, toName: string, };
