// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Expr } from "./Expr";

/**
 * One `StatusField` template.
 */
export type FieldTemplate = { label: string, value: Expr, emphasis?: Expr, };
