// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScopeEntity } from "./ScopeEntity";

/**
 * The player's inventory in the widened ViewModel.
 */
export type Inventory = { items: Array<ScopeEntity>, keys: Array<ScopeEntity>, equippedNames: Array<string>, slots: bigint, };
