// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Stmt } from "./Stmt";

/**
 * An item's author-defined behavior: effect bodies fired when the item is
 * used or read. Both are effect bodies (`Vec<Stmt>`, `allow_pass=false`),
 * identical in shape to mechanic hook bodies. Absent hook = no-op.
 */
export type ItemScript = { onUse?: Array<Stmt>, onRead?: Array<Stmt>, };
