// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Direction } from "./Direction";

/**
 * An impassable (locked) exit.
 */
export type LockedDoorView = { name: string, dir: Direction, };
