// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScopeEntity } from "./ScopeEntity";

/**
 * A loot container with its resolved contents.
 */
export type LootView = { id: string, description: string, opened: boolean, contents: Array<ScopeEntity>, };
