// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One component of the shared material pool, for the HUD readout.
 */
export type MaterialView = { component: string, quantity: bigint, };
