// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MechanicHooks } from "./MechanicHooks";
import type { Stmt } from "./Stmt";

/**
 * A campaign-authored mechanic behavior: a literal state seed, the six hooks,
 * and custom actions keyed by action key.
 */
export type MechanicScript = { 
/**
 * Literal JSON state seed. Deliberately plain data, NOT an Expr.
 */
init: unknown, hooks: MechanicHooks, 
/**
 * Custom actions, keyed by action key. Always emitted (even when empty):
 * the checked-in goldens always write `actions: {}`, and the ts-rs binding
 * marks it required (not `ts(optional)`); `default` keeps older catalogs
 * that lack `actions` deserializable.
 */
actions: { [key in string]?: Array<Stmt> }, };
