// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DamageBody } from "./DamageBody";
import type { Stmt } from "./Stmt";

/**
 * The six mechanic hook bodies. Each is optional; a missing hook is a no-op
 * at dispatch.
 */
export type MechanicHooks = { onRoundStart?: Array<Stmt>, onRoundEnd?: Array<Stmt>, onTurnStart?: Array<Stmt>, onTurnEnd?: Array<Stmt>, onAction?: Array<Stmt>, modifyDamage?: DamageBody, };
