// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StatType } from "./StatType";

/**
 * A single mob-on-player strike, surfaced for typed combat feedback.
 * `amount` is an effective-stat delta (f64, per the stat model).
 */
export type MobAttack = { name: string, stat: StatType, amount: number, };
