// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StatType } from "./StatType";

/**
 * A mob's innate attack (the `naturalAttack` field on a mob snapshot). Always
 * present on a spawned mob; the native default is `{stat:"health",power:1}`.
 */
export type NaturalAttack = { stat: StatType, power: number, };
