// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionKind } from "./ActionKind";
import type { CampaignOutcome } from "./CampaignOutcome";
import type { EntityRef } from "./EntityRef";
import type { MechanicCue } from "./MechanicCue";
import type { OutcomeNarration } from "./OutcomeNarration";
import type { StatusField } from "./StatusField";

export type PresentationCue = { "kind": "action", action: ActionKind, actor: EntityRef, sound: unknown, } | { "kind": "encounter", mob: EntityRef, room: EntityRef, sound: unknown, } | { "kind": "visibility", room: EntityRef, lit: boolean, } | { "kind": "resolution", outcome: CampaignOutcome, reason: string | null, narration: OutcomeNarration | null, } | { "kind": "mechanic", cue: MechanicCue, } | { "kind": "status", fields: Array<StatusField>, };
