// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A recipe the party knows, with whether the pool can currently afford it. Drives
 * the craft menu / `craft <name>` resolution.
 */
export type RecipeView = { id: string, name: string, affordable: boolean, };
