// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The closed set of first-class script values. Serialized UNTAGGED so
 * authored literals read as plain JSON (`5`, `"x"`, `true`, `[..]`,
 * `null`). Numbers are f64 (JS `number` semantics).
 */
export type ScriptValue = boolean | number | string | Array<ScriptValue> | null;
