// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The three core character stats. Wire values are exactly
 * `"energy" | "sanity" | "health"`, as pinned by the conformance goldens.
 */
export type StatType = "energy" | "sanity" | "health";
