// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EffectTemplate } from "./EffectTemplate";
import type { Expr } from "./Expr";

/**
 * A statement in an effect/script body. Tagged on `kind`.
 */
export type Stmt = { "kind": "guard", cond: Expr, } | { "kind": "when", cond: Expr, then: Array<Stmt>, } | { "kind": "setState", field: string, value: Expr, } | { "kind": "setStateIn", mapField: string, key: Expr, value: Expr, } | { "kind": "emit", effect: EffectTemplate, } | { "kind": "pass", value: Expr, };
