// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Expr } from "./Expr";

/**
 * A campaign-authored victory condition: a boolean `test` expression.
 */
export type VictoryScript = { test: Expr, };
