// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CampaignOutcome } from "./CampaignOutcome";
import type { ExitView } from "./ExitView";
import type { Inventory } from "./Inventory";
import type { LockedDoorView } from "./LockedDoorView";
import type { LootView } from "./LootView";
import type { MaterialView } from "./MaterialView";
import type { RecipeView } from "./RecipeView";
import type { ScopeEntity } from "./ScopeEntity";
import type { StatusView } from "./StatusView";
import type { ThinRoom } from "./ThinRoom";
import type { VillainView } from "./VillainView";

/**
 * The widened ViewModel.
 */
export type ViewModel = { room: ThinRoom, exits: Array<ExitView>, lockedDoors: Array<LockedDoorView>, occupants: Array<ScopeEntity>, loot: Array<LootView>, 
/**
 * Un-harvested material caches in the room (scope entities of kind `cache`).
 */
caches: Array<ScopeEntity>, inventory: Inventory, scope: Array<ScopeEntity>, 
/**
 * The shared material pool, sorted by component.
 */
materials: Array<MaterialView>, 
/**
 * Recipes the party knows (with current affordability).
 */
recipes: Array<RecipeView>, status: StatusView, outcome: CampaignOutcome, finished: boolean, 
/**
 * The Villain panel. Absent (and omitted on serialize) when no villain is
 * designated, so pre-villain ViewModel goldens stay byte-stable.
 */
villain?: VillainView, 
/**
 * Rounds of supernatural darkness remaining (the `wicked:lights-out`
 * card). Absent while inactive, keeping pre-villain goldens byte-stable.
 */
lightsOutRounds?: bigint, };
