// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardView } from "./CardView";

/**
 * The Villain panel: who the villain is, the hand (faces resolved from the
 * catalog), pile counts, and whether this turn's card action is spent. Only
 * projected for the viewing seat when a villain is designated.
 */
export type VillainView = { characterId: string, name: string, 
/**
 * True when the viewing character IS the villain — surfaces show the hand
 * face-up only then.
 */
isYou: boolean, hand: Array<CardView>, deckCount: bigint, discardCount: bigint, cardActionTaken: boolean, };
